apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-authd-pass
  labels:
  {{- include "wazuh.labels" . | nindent 4 }}
data:
  authd.pass: {{ required "authd.password is required" .Values.cred.authd.password
    | b64enc }}